export interface Room {
  id: number;          // auto‑generated by DB (or client)
  roomNo: string;      // unique string (e.g. "A101")
  capacity: number;    // max number of students
  hasAC: boolean;
  hasAttachedWashroom: boolean;
}